---
- name: Create User
  hosts: all
  become: true
  become_method: sudo
  vars:
    uname: user1
    ugroups: user1
    ucomment: "None"
    pub_key_file: "/Path/ssh_key.pub"

  roles:
    - create_user
