---
- name: Generate Password, string
  hosts: localhost
  gather_facts: false

  vars_prompt:
  - name: "my_password"
    prompt: "Enter password "
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes
    salt_size: 7

  tasks:
  - name: Encrypt password string as a shadow
    debug:
      msg: "password: '{{ my_password }}'"
